import type { Metadata } from "next";
import "./globals.css";
import Nav from "./Nav";
import { Work_Sans } from 'next/font/google'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = Work_Sans({ subsets: ['latin'], weight: [
  "100", "200", "300", "400", "500", "600", "700", "800", "900"
] })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className}`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
